const questions = [
{id:1,question:`‘पत्नी’ या शब्दाला समानार्थी शब्द कोणता?`,options:[`धव`,`भर्ता`,`कान्ता`,`कलत्र`]},
{id:2,question:`‘वाईट कृत्य करणाऱ्याला ते उघडकीस येईल की काय याची सतत भीती वाटते’ या अर्थाची म्हण कोणती?`,options:[`बळी तो कान पिळी`,`चोराच्या मनात चांदणे`,`कर नाही त्याला डर कशाला`,`दिव्याखाली अंधार`]},
{id:3,question:`‘सोने’ या शब्दाला पर्यायी समानार्थी शब्द निवडा.\n(a) कनक  (b) सुवर्ण  (c) हेम  (d) कांचन`,options:[`फक्त (a) व (b) बरोबर`,`फक्त (a), (b) व (d) बरोबर`,`फक्त (c) व (d) बरोबर`,`सर्व पर्याय बरोबर`]},
{id:4,question:`खालीलपैकी देशी शब्दांचा शब्दगट ओळखा.`,options:[`तंबाखू, बशी, चावी, प्रीती`,`साबण, फणस, हापूस, कोबी`,`बाजरी, चिमणी, बोका, ओसरी`,`कागद, मिठाई, नोकरी, दवाखाना`]},
{id:5,question:`‘जो गरीब असतो त्याला केलेली गोष्ट नसते आणि ज्याला केलेली गोष्ट असते त्याला अनुकूलता नसते.’ या वाक्याचा प्रकार ओळखा.`,options:[`केवळ संयुक्त`,`मिश्र संयुक्त`,`मिश्र वाक्य`,`केवळ मिश्र संयुक्त`]},
{id:6,question:`दंड नसलेले व्यंजन शोधा.`,options:[`रक्त`,`कष्ट`,`अल्प`,`अर्पण`]},
{id:7,question:`‘हर्ष’ चा विरुद्धार्थी शब्द कोणता?`,options:[`आनंद`,`हानी`,`खेद`,`मोद`]},
{id:8,question:`‘आपली पाठ आपणास दिसत नाही’, या वाक्यातील ध्वन्यार्थ पुढे दिलेल्या पर्यायातून निवडा.`,options:[`दुसऱ्यांचे दोष दिसत नाहीत.`,`स्वतःचे दोष स्वतःला दिसत नाहीत.`,`स्वतःचे गुण स्वतःला दिसतात.`,`दुसऱ्यांचे गुण दिसतात.`]},
{id:9,question:`‘गोडवा’ हा शब्द कोणत्या नामाचा प्रकार आहे?`,options:[`सामान्यनाम`,`विशेषनाम`,`दर्शकनाम`,`भाववाचकनाम`]},
{id:10,question:`‘मी तुला रामकडून पाच रुपये देववीन’, या वाक्यातील क्रियापदाचा प्रकार ओळखा.`,options:[`भावकर्तृक क्रियापद`,`संयुक्त क्रियापद`,`प्रयोजक क्रियापद`,`सहाय क्रियापद`]},
{id:11,question:`‘पारध्याकडून मोर पकडला गेला’ या वाक्यातील प्रयोगाचा उपप्रकार ओळखा.`,options:[`कर्तरी`,`शक्य कर्मणी`,`कर्मकर्तरी`,`भावे`]},
{id:12,question:`समानार्थी शब्दांच्या जोड्या जुळवा.\n‘अ’: (a) अमृत, (b) पोपट, (c) अनल, (d) चंद्र\n‘ब’: (i) शुक, (ii) विस्तव, (iii) हिमांशू, (iv) सुधा`,options:[`(a)-(iv), (b)-(i), (c)-(ii), (d)-(iii)`,`(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)`,`(a)-(iii), (b)-(iv), (c)-(i), (d)-(ii)`,`(a)-(ii), (b)-(iii), (c)-(iv), (d)-(i)`]},
{id:13,question:`अफलातून, जुलूम, कबूल हे शब्द कोणत्या भाषेतील आहेत?`,options:[`इंग्रजी`,`पोर्तुगीज`,`फारसी`,`अरबी`]},
{id:14,question:`खालीलपैकी कोणते देवनागरी लिपीचे वैशिष्ट्य आहे?\n(a) वर्णमालेचे वैज्ञानिक वर्गीकरण\n(b) एक ध्वनी, एक लिपिचिन्ह\n(c) एक चिन्ह, एक ध्वनी\n(d) उच्चारण लेखनासाठी एकरूपता`,options:[`फक्त (a) व (b) बरोबर`,`सर्व पर्याय बरोबर`,`फक्त (c) व (d) बरोबर`,`फक्त (a), (b) व (c) बरोबर`]},
{id:15,question:`कल्याची किंवा कर्माची क्रियापदाशी अशी जी जुळणी, ठेवण किंवा रचना असते, तिला काय म्हणतात?`,options:[`विभक्ती`,`धातुसाधिते`,`आख्यात`,`प्रयोग`]},
{id:16,question:`‘मुंबईस जाताना खंडाळ्याजवळ उजाडले’ हे वाक्य कोणत्या प्रयोगाचे लक्षण आहे?`,options:[`मिश्र संकर प्रयोग`,`कर्मभाव संकर प्रयोग`,`भाव कर्तरी प्रयोग`,`कर्मणी प्रयोग`]},
{id:17,question:`यावर्षी बाजारात सूर्यफुलाची खूप आवक आहे. या वाक्यातील अधोरेखित शब्दाचा विरुद्धार्थी शब्द कोणता?`,options:[`संगम`,`जावक`,`आयात`,`आगम`]},
{id:18,question:`‘त्यांच्या मनात काहीतरी गौड आहे’ या वाक्यातील अधोरेखित शब्दासाठी अयोग्य अर्थ असणारा शब्द निवडा.`,options:[`दोष`,`व्यंग`,`व्याधी`,`रहस्य`]},
{id:19,question:`ज्या वाक्यातील क्रियापदाच्या रूपावरून अमुक केले असते तर अमुक झाले असते अशी अट किंवा संकेत असा अर्थ निघत असेल तर त्यास कोणत्या प्रकारचे वाक्य म्हणावे?`,options:[`संकेतार्थी`,`आज्ञार्थी`,`नकारार्थी`,`विधानार्थी`]},
{id:20,question:`खालील शब्दांपैकी कोणते सामान्यरूप चुकीचे आहे?`,options:[`घरात`,`येण्याचे`,`करणीत`,`फौजांनी`]},
{id:21,question:`‘उंचच्या उंच डोंगर चढताना लोंढे काकांच्या नाकी नऊ आले’ या विधानातील वाक्प्रचाराचा अर्थ सांगा.`,options:[`पायाला गोळे येणे`,`जीवात जीव येणे`,`जीव टांगणीला लागणे`,`प्राण कासावीस होणे`]},
{id:22,question:`“दुसऱ्याने आपल्या विरोधात तक्रार करण्यापूर्वी आपणच त्या विरोधात तक्रार करावी”, हा आशय स्पष्ट करणारी म्हण ओळखा.`,options:[`अटकळ्या देवा दंडवत`,`आदपाव भोपळा आणि अडीच शेर तेल`,`अवसबाई तुझ्याकडे, पुनवबाई तुझ्याकडे`,`अस्सलआधी आरोळी`]},
{id:23,question:`शब्दशः होणाऱ्या अर्थापेक्षा भिन्न व विशिष्ट अर्थाने रूढ होऊन बसलेल्या शब्दसमूहाला काय म्हणतात?`,options:[`विशेषण`,`वाक्प्रचार`,`शब्दशक्ती`,`शब्दजाती`]},
{id:24,question:`‘मुले मोजून पाहिली, पण ती वीसच भरली,’ वाक्याचा प्रकार ओळखा.`,options:[`केवळ वाक्य`,`संयुक्त वाक्य`,`मिश्र वाक्य`,`स्वार्थी वाक्य`]},
{id:25,question:`खालील शब्दसमूहांपैकी अंशाभ्यस्त शब्दसमूह ओळखा.`,options:[`गोलंबिला, आंबटचिंबट, उलटासुलटा`,`रानरान, खोलोखोल, मागोमाग`,`गडगडाट, घमघम, गदगद`,`पळापळ, डागमागणे, कडकडाट`]},
{id:26,question:`‘रसिक’ हा शब्द ______ आहे.`,options:[`उपसर्गघटित शब्द`,`अभ्यस्त शब्द`,`प्रत्ययघटित शब्द`,`सामासिक शब्द`]},
{id:27,question:`‘तप घालीत बसणे’, या वाक्प्रचाराचा अर्थ खालीलपैकी कोणता?`,options:[`तप करून बसणे`,`अंतर्मुख होऊन बसणे`,`तपश्चर्या करणे`,`प्रार्थना करणे`]},
{id:28,question:`पुढील शब्दांपैकी तत्सम शब्द ओळखा.`,options:[`उत्सव`,`पान`,`आग`,`विनंती`]},
{id:29,question:`‘अपमान केल्यास कुणाला राग येत नाही’ या वाक्याचे होकारार्थी वाक्य करा.`,options:[`अपमान केल्यास राग येणार नाही का?`,`अपमान केल्यास राग का येऊ नये?`,`अपमान केल्यास प्रत्येकाला राग येतोच.`,`अपमान केल्यास राग का यावा.`]},
{id:30,question:`‘तो उत्तीर्ण झाल्यामुळे सर्वांना आनंद झाला’, या वाक्याचा प्रकार ओळखा.`,options:[`संयुक्त वाक्य`,`केवळ वाक्य`,`प्रश्नार्थी वाक्य`,`उद्गारार्थी वाक्य`]},
{id:31,question:`बंडा देसायाच्या अकाली निधनानंतर वाड्यातल्या विहाडकरांचेच वाड्याचा ताबा मिळविला. या आशयाची योग्य म्हण ओळखा.`,options:[`चोराच्या मनात चांदणे`,`गोगलगाय पोटात पाय`,`आयत्या बिळावर नागोबा`,`थेंबे थेंबे तळे साचे`]},
{id:32,question:`‘आई बापासारखीच मुले असतात’ हा आशय स्पष्ट करणारी म्हण ओळखा.`,options:[`अनुभवाच्या खाणी`,`बाप बेटा सवाई`,`खाण तशी माती`,`घरोघरी मातीच्या चुली`]},
{id:33,question:`‘प्रथमग्रासे मक्षिकापातः’ या म्हणीचा अर्थ काय?`,options:[`पहिल्या घासाला मधमाशी सापडली.`,`एखादी चांगली गोष्ट सुरू होताच त्यात विघ्न येणे.`,`पहिल्या घासाला आनंद झाला.`,`पहिल्या घासाची चव चांगली असते.`]},
{id:34,question:`नामाच्या व सर्वनामाच्या ठिकाणी संख्या सुचविण्याचा धर्म असतो त्यास ______ म्हणतात.`,options:[`आख्यात`,`कारकार्थ`,`पूरक`,`वचन`]},
{id:35,question:`‘त्याने आपल्या मुलीला कालच सासरी पाठविलेन.’ या वाक्यातील प्रयोग ओळखा.`,options:[`कर्तृकर्म संकर`,`कर्तृकर्मभावे संकर`,`कर्मभावे संकर`,`कर्तृभावे संकर`]},
{id:36,question:`धातूला विविध प्रत्यय लागून क्रिया अपुरी दाखविणाऱ्या शब्दांना काय म्हणतात?`,options:[`धातू`,`धातुसाधिते`,`विशेषण`,`शक्य क्रियापदे`]},
{id:37,question:`‘मलिन’ या शब्दाच्या विरुद्धार्थी शब्दाचा खालीलपैकी कोणत्या वाक्यात उपयोग केला आहे?`,options:[`स्वच्छतेचे पालन करावे.`,`तो मळलेल्या कपड्यानिशी गावी गेला.`,`घाणेरड्या नजरेने तो माझ्याकडे पाहत होता.`,`निर्मळ अंतःकरणाने ती कधी वागलीच नाही.`]},
{id:38,question:`‘काल सकाळी बाजूच्या मैदानावर सचिन जोरात धावला’ हे वाक्य कोणत्या प्रकारचे आहे?`,options:[`विधेय विस्तार`,`कर्म विस्तार`,`कर्मपूरक`,`विधीपूरक`]},
{id:39,question:`‘शेतकऱ्यांना मिळणारे सरकारी कर्ज’, या शब्दसमूहासाठी योग्य पर्यायी शब्द निवडा.`,options:[`अनुदान`,`तगाई`,`सानुग्रह`,`धनादेश`]},
{id:40,question:`‘शिडीवर चढून डबा काढ’ या वाक्यातील अधोरेखित शब्द कोणत्या प्रकारचा आहे?`,options:[`क्रियाविशेषण अव्यय`,`शब्दयोगी अव्यय`,`उभयान्वयी अव्यय`,`विकल्पबोध अव्यय`]},
{id:41,question:`‘वेदांश हा प्रश्न विचारातच योग्य ते उत्तर ताबडतोब देणारा विद्यार्थी आहे,’ अधोरेखित शब्दसमूहासाठी एक शब्द सांगा.\n(a) स्थितबुद्धी (b) स्थितमती (c) हजरजबाबी (d) मनकवडा`,options:[`(a) आणि (b)`,`(b) आणि (d)`,`(c)`,`(d)`]},
{id:42,question:`देवी + औदार्य या पोटशब्दापासून तयार होणारा योग्य जोडशब्द ओळखा.`,options:[`देवदार्य`,`देवीदार्य`,`देवीऔदार्य`,`देव्यौदार्य`]},
{id:43,question:`खालील ‘होकारार्थी’ वाक्याचे ‘नकारार्थी’ वाक्य करा.\nया लोकांचे अज्ञान पाहून मला दुःख होते.`,options:[`या लोकांचे अज्ञान पाहून मला दुःख होत नाही.`,`या अज्ञानी लोकांचे काय होणार?`,`या अज्ञानी लोकांनी शिक्षण घ्यावे.`,`या लोकांचे अज्ञान पाहून मला सुख होत नाही.`]},
{id:44,question:`उद्देशाचे प्रथमोपस्थित संघटक कोणते?`,options:[`मूळ उद्देश्य व मूळ विधेय`,`मूळ उद्देश्य व विधेयविस्तार`,`विधेयविस्तार व विधेयपूरक`,`मूळ उद्देश्य व उद्देश्यविस्तार`]},
{id:45,question:`‘______ जगले तरच भविष्यात प्राणवायू मिळणार आहे.’ या वाक्यातील रिकाम्या जागी तत्सम शब्दाचा वापर करा.`,options:[`झाड`,`वृक्ष`,`रोप`,`वेल`]},
{id:46,question:`भाषेचे अंतिम उपयोजन कोणते?`,options:[`धर्मप्रसार`,`साहित्यनिर्मिती`,`दैनंदिन व्यवहार`,`प्रशासकीय व्यवहार`]},
{id:47,question:`प्रारंभी युरोपीय राष्ट्रवादाचे मूलाधार कोणते होते?`,options:[`लोकभाषा व वाङ्मयनिर्मिती`,`भाषांतरे आणि संस्कृती`,`भाषा, वंश आणि संस्कृती`,`भौगोलिकता, धार्मिकता आणि भाषा`]},
{id:48,question:`कोणत्याही समाजाला राष्ट्र ही पात्रता प्राप्त होण्यासाठी कोणती गोष्ट आवश्यक असते?`,options:[`साहित्यनिर्मिती करण्याची क्षमता`,`धर्म आणि देवत कल्पना`,`लोकभाषा व संस्कृती`,`भाषांतर करण्याची क्षमता`]},
{id:49,question:`सांस्कृतिक संक्रमणाचे महत्त्वाचे माध्यम कोणते?`,options:[`राष्ट्रवाद`,`वंश`,`धर्म`,`भाषा`]},
{id:50,question:`वेगवेगळ्या धर्मचिंतकांनी धर्मचिंतनासाठी कोणत्या भाषेचा आधार घेतला?`,options:[`वैदिक भाषा`,`संस्कृत भाषा`,`प्रमाण भाषा`,`लोकभाषा`]},
{id:51,question:`It is always desirable / to listen to the advice / who have extensive practical experience / No error. Spot the error in the sentence.`,options:[`(a)`,`(b)`,`(c)`,`(d)`]},
{id:52,question:`Select the grammatically correct sentence/s.\n(a) Neither did men nor women go out at night.\n(b) Not only the kitten was wet but cold also.\n(c) No sooner does the curtain go up when the children watch the play closely.`,options:[`Only (a)`,`Only (b)`,`Only (a) and (b)`,`Only (c)`]},
{id:53,question:`______ pronouns are always singular. Which of the following correctly fills in the blank?\n(a) Reciprocal (b) Relative (c) Personal (d) Distributive`,options:[`(c) only`,`(a) only`,`(d) only`,`both (b) and (d)`]},
{id:54,question:`Choose the idiom that means “to reveal a secret or confidential information”.`,options:[`Break the ice.`,`Let the cat out of the bag.`,`Bite the bullet.`,`Hit the nail on the head.`]},
{id:55,question:`Choose the correct sentences:\n(a) Try and come tomorrow.\n(b) I felt sure he would die and his money would go to his son.\n(c) The pundit read the first mantra and the bridegroom read the second.`,options:[`(c) only`,`(b) only`,`(b) and (c) only`,`(a), (b) and (c)`]},
{id:56,question:`Find the correct indirect speech sentence for: He said, “I shall go home.”`,options:[`He says that he shall go home.`,`He said that he shall go home.`,`He said that he would go home.`,`He says that he would go home.`]},
{id:57,question:`Had he not sent money on time, the poor farmer ______ his son? Select the correct alternative.`,options:[`would lost`,`would have lost`,`would have been lost`,`will have lost`]},
{id:58,question:`Fill in the blank. Many people are painting ______.`,options:[`white their houses these days`,`these days white their houses`,`their houses white these days`,`their houses these days white`]},
{id:59,question:`After years of guilt, she finally decided to make a clean breast of her involvement in the scandal and confessed everything to the authorities. What does “make a clean breast of” mean?`,options:[`To clean something thoroughly`,`To reveal or confess something`,`To make heartfelt apology`,`To face the consequences of one’s actions`]},
{id:60,question:`Identify the sentence/s with adverbial clause.\n(a) The doctor advised his patient where he should go for a holiday.\n(b) The judge wondered who had committed the crime.\n(c) It is a pity that you couldn’t come.\n(d) Although aeroplanes sometimes crash, accidents are rare.`,options:[`Only (a) and (c)`,`Only (b) and (d)`,`Only (a) and (b)`,`Only (d)`]},
{id:61,question:`Fill in the blank: “Manisha will ______ the prize which is declared yesterday.”`,options:[`Except`,`Accept`,`Acsept`,`Exept`]},
{id:62,question:`Find the correct option of the question tag for “They will fail.”\n(a) They will fail, will they?\n(b) They will fail, would they?\n(c) They will fail, won’t they?\n(d) They will fail, will not they?`,options:[`(a) and (b)`,`(b) and (d)`,`(c) and (d)`,`Only (c)`]},
{id:63,question:`“I knew that he was ill, but I did not know that he suffered from cancer.” The sentence exemplifies:`,options:[`Compound sentence`,`Compound-Complex sentence`,`Complex sentence`,`Simple sentence`]},
{id:64,question:`Choose the correct sentences:\n(a) Can you tell me why you’re interested in an administrative career?\n(b) Can you tell me why you are late?\n(c) Do you think does your name indicate your personality?`,options:[`(c) only`,`(a) and (b) only`,`(b) and (c) only`,`(a), (b) and (c)`]},
{id:65,question:`Fill in the blanks with the correct pair of articles: ______ death of the Prime Minister is being grieved by many people in ______ UK.`,options:[`the, an`,`the, the`,`a, an`,`a, the`]},
{id:66,question:`Choose the correct idiom: The President was ______ and lived beyond his tenure.`,options:[`hale and hearty`,`quite a catch`,`talking by the dozen`,`head over heels`]},
{id:67,question:`Choose the correct meaning of the underlined word: “The staff members are conversant with the issues.”`,options:[`Frosty`,`Unfriendly`,`Unknown`,`Familiar`]},
{id:68,question:`Select the correct meaning of the idiom: “My father burnt his fingers by interfering in his neighbour’s affair.”`,options:[`Got opportunity for revenge`,`Got himself into trouble`,`Got injury on fingers`,`Got worried for his fingers`]},
{id:69,question:`Choose the word closest to the opposite in meaning of “pragmatic” in: “The leader was pragmatic in his approach to the peoples’ problems.”`,options:[`Indefinite`,`Vague`,`Optimistic`,`Idealistic`]},
{id:70,question:`Identify the correct sentences:\n(a) I met Renu after I had finished my work.\n(b) When I first seeing him, I thought he was a lawyer.\n(c) He joined after had his dinner.`,options:[`(a) only`,`(a) and (b) only`,`(a) and (c) only`,`(a), (b) and (c)`]},
{id:71,question:`Find out the meaning of the word “forever” as used in the following sentences:\n(a) She is forever interrupting the conversation.\n(b) She has left him forever.`,options:[`(a) Previously; (b) Currently`,`(a) Officially; (b) Previously`,`(a) Endlessly; (b) Permanently`,`(a) Permanently; (b) Endlessly`]},
{id:72,question:`Identify the form of the underlined verb in the sentence: “Swimming is a good exercise.”`,options:[`Infinitive`,`Gerund`,`Phrase`,`Clause`]},
{id:73,question:`Choose the correct meaning of “cut down” in the sentence: “The government must cut down its expenditure.”`,options:[`obtain`,`increase`,`reduce`,`stop`]},
{id:74,question:`Choose the correct reported speech of the following sentence:\nHe said, “I do not wish to see any of you; go away.”`,options:[`He said that he did not wish to see any of them and ordered them to go away.`,`He told that he did not wish to see any one of them and punished them to went away.`,`He exclaimed them that he did not wish to see them and even told them to go away.`,`He said to them that he did not wish to see anyone of them and told them to go away.`]},
{id:75,question:`Choose the correct sequencing of the following sentence:\nThe students are\n(a) with the help\n(b) for last two hours\n(c) of the teacher\n(d) solving the questions`,options:[`(d), (c), (a), (b)`,`(d), (a), (c), (b)`,`(d), (a), (b), (c)`,`(d), (b), (c), (a)`]},
{id:76,question:`Choose the one-word substitute for “people living in the same age.”`,options:[`Delegate`,`Cosmopolitan`,`Curator`,`Contemporaries`]},
{id:77,question:`“After years of searching for answers, she had an epiphany and finally understood the true meaning of happiness.” Which phrase represents the word “epiphany”?`,options:[`A sudden realization or insight`,`A feeling of confusion or uncertainty`,`A state of complete contentment`,`A strong sense of empathy`]},
{id:78,question:`“He must be asleep for there is no light in his room.”\nThe underlined conjunction expresses ______ and hence is called ______ conjunction.\n(a) inference, illative\n(b) addition, copulative\n(c) contrast, adversative\n(d) choice, alternative`,options:[`(c) only`,`(a) only`,`(d) only`,`(b) only`]},
{id:79,question:`Everybody ______ speak the truth. Complete the sentence by choosing the correct alternative.`,options:[`should`,`would`,`will`,`may`]},
{id:80,question:`Match the following pairs with the correct meaning:\n(a) Ignorant — (ii) Uniformed\n(b) Imminent — (iv) Approaching\n(c) Obstinate — (i) Stubborn\n(d) Prudent — (iii) Wise`,options:[`(a)-(ii), (b)-(iv), (c)-(i), (d)-(iii)`,`(a)-(iii), (b)-(iv), (c)-(i), (d)-(ii)`,`(a)-(ii), (b)-(iii), (c)-(i), (d)-(iv)`,`(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)`]},
{id:81,question:`Choose the meaning of the underlined idiom: “How can you trust a man who plays fast and loose?”`,options:[`Corrupt nature`,`Who is not existing`,`Vicious`,`Says one thing and does another`]},
{id:82,question:`Which of the following is/are correct with respect to Relative Pronoun agreement?\n(a) It is I who am to blame.\n(b) It is I who is to blame.\n(c) It is me who is to blame.\n(d) It is I who is to be blamed.`,options:[`(b) only`,`both (a) and (d)`,`(a) only`,`(c) only`]},
{id:83,question:`Match the words from A with their correct meaning from B.\nA: (a) Annihilate, (b) Celibacy, (c) Indefatigable, (d) Somnambulist\nB: (i) One who walks in sleep, (ii) One incapable of being tired, (iii) The state of remaining unmarried, (iv) To destroy completely`,options:[`(a)-(i), (b)-(ii), (c)-(iii), (d)-(iv)`,`(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)`,`(a)-(iv), (b)-(i), (c)-(iii), (d)-(ii)`,`(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)`]},
{id:84,question:`Find the correct meaning of the underlined idiom: “Why are you hanging back? You sing as well as anyone else.”`,options:[`To hesitate to proceed`,`To repeat`,`To break the voice`,`To come late`]},
{id:85,question:`“If I had wings, I would come flying to you.” Which condition is expressed?\n(a) Impossible condition\n(b) Improbable condition\n(c) Probable condition\n(d) Likely condition`,options:[`(d) only`,`(a) only`,`(c) only`,`(b) only`]},
{id:86,question:`Select the idiom that means “to try to achieve something that is difficult or unlikely.”`,options:[`Turn over a new leaf`,`Throw in the towel`,`Beat the dead horse`,`Reach for the stars`]},
{id:87,question:`“Those who are ______ in the art of flattery make a rapid progress in their life.” Select the correct word.`,options:[`adopt`,`adept`,`adapt`,`about`]},
{id:88,question:`Find the correct meaning of the underlined idiom: “Unless a poet is in his element, he cannot write good poetry.”`,options:[`In his home`,`In his job`,`In his`,`In the right mood`]},
{id:89,question:`Match the following:\n(a) Demonstrative pronouns\n(b) Emphatic pronouns\n(c) Interrogative pronouns\n(d) Indefinite pronouns\n(i) myself, herself; (ii) what, which; (iii) anyone, everybody; (iv) This, that`,options:[`(a)-(iii), (b)-(i), (c)-(ii), (d)-(iv)`,`(a)-(iv), (b)-(i), (c)-(ii), (d)-(iii)`,`(a)-(ii), (b)-(iv), (c)-(i), (d)-(iii)`,`(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)`]},
{id:90,question:`Identify the wrongly spelt word/s:\n(a) Accept  (b) Anciant  (c) Attract  (d) Arrive`,options:[`(b) and (d)`,`Only (a)`,`(b) and (c)`,`Only (b)`]},
{id:91,question:`Identify the grammatically correct sentence/s.\n(a) He is the man whom we all respect.\n(b) I don’t know why she like dogs.\n(c) His endeavours needs to be rewarded.\n(d) Give me some food which I may eat.`,options:[`(a) and (b) only`,`(b) and (c) only`,`(a) and (d) only`,`(a) and (c) only`]},
{id:92,question:`Find the correct synonym for the word “Tranquil”.`,options:[`Agitated`,`Angry`,`Quiet`,`Disturbed`]},
{id:93,question:`Find the correct matching option:\n(a) Altar\n(b) Alter\n(c) Affection\n(d) Affectation\n(i) Pretence, false show; (ii) Place of worship; (iii) To change; (iv) Love, dedicate, emotions of liking`,options:[`(a)-(i), (b)-(ii), (c)-(iii), (d)-(iv)`,`(a)-(ii), (b)-(i), (c)-(iv), (d)-(iii)`,`(a)-(ii), (b)-(iii), (c)-(iv), (d)-(i)`,`(a)-(iv), (b)-(ii), (c)-(i), (d)-(iii)`]},
{id:94,question:`The politician’s response to the accusation simply begged the question and failed to provide a clear answer. What does the phrase “to beg the question” mean?`,options:[`To ask for a favour or assistance`,`To avoid answering the question directly`,`To make a logical fallacy by assuming the conclusion in premise`,`To question someone’s authority or credibility`]},
{id:95,question:`Choose the correct sentences.\n(a) Her work is superior than her brother’s.\n(b) This photograph is the better of the two.\n(c) This little girl is better than clever.`,options:[`(b) only`,`(a) and (b) only`,`(b) and (c) only`,`(a), (b) and (c)`]},
{id:96,question:`Deep Learning algorithms can be corrected on the basis of error-feedback provided by ______.\n(a) Layers of interconnected neurons\n(b) Fraudulent transactions in banking\n(c) Back-propagation\n(d) Data Management System (DMS)`,options:[`(b) only`,`(a) only`,`(d) only`,`(c) only`]},
{id:97,question:`Basically speaking, Deep Learning is a ______.\n(a) Neural Module\n(b) Hot topic in the world of Artificial Intelligence (AI)\n(c) Data Management Strategy\n(d) Back-Propagation technique`,options:[`(d) only`,`(c) only`,`(a) only`,`(b) only`]},
{id:98,question:`Deep Learning plays a very important role in ______.\n(a) identifying the structure of human brain\n(b) the treatment, classification, analysis and security of data\n(c) controlling the dropout and Rectified Linear Units (ReLU)\n(d) measuring the depth of layers in neural networks`,options:[`(c) only`,`(b) only`,`(a) only`,`(d) only`]},
{id:99,question:`One important feature of Deep Learning is that ______.\n(a) Deep Learning requires a Chief Data Officer (CDO)\n(b) Deep Learning is a module not requiring labelled data to learn from\n(c) Deep Learning is a subset of Artificial Intelligence (AI)\n(d) Deep Learning is more efficient than Machine Learning (ML)`,options:[`(d) only`,`(c) only`,`(b) only`,`(a) only`]},
{id:100,question:`Deep Learning is a part of ______.\n(a) AlexNet\n(b) ChatGPT\n(c) Machine Learning (ML)\n(d) Natural Language Processing (NLP)`,options:[`(c) only`,`(b) only`,`(d) only`,`(a) only`]},
];

// Final key for question-paper set A (published 5 March 2024).
// Values are zero-based option indexes. null means the question was cancelled.
const answerKey = [
  null,1,3,2,1,3,2,1,3,2,2,0,3,1,3,2,1,2,0,2,3,3,1,1,0,
  2,1,0,2,1,2,2,1,3,1,1,3,0,1,1,2,3,3,3,1,3,2,0,3,3,
  null,0,2,1,0,2,1,2,1,3,1,3,1,1,1,0,3,1,3,0,2,1,2,0,1,
  3,0,1,0,0,3,2,3,0,3,3,1,3,1,3,2,2,2,2,0,3,1,1,2,0
];

questions.forEach((item, index) => {
  item.answer = answerKey[index];
  item.cancelled = answerKey[index] === null;
});

const deepLearningPassage = `Data Management is one of the hardest and costliest tasks every organization faces. The fact that organizations appoint a Chief Data Officer (CDO) shows how much importance they give to managing data—its treatment, classification, analysis, security and compliance. This is where Deep Learning (DL) shines as a perfect data management strategy when employed with the right set of tools.

While DL has been around for a while, the recent popularity of ChatGPT brings it back to being a hot topic in the world of AI. Deep Learning is a subset of Machine Learning (ML) and is based on how the human brain is structured and works. DL uses artificial neural networks to learn from large amounts of data. It gets the name “deep” because it leverages multiple layers of interconnected neurons to process and learn from the data. DL algorithms are capable of learning complex patterns in images, audio and text. Deep learning uses large amounts of unlabelled data to learn the underlying structure and patterns in data. It is an unsupervised learning module that does not require labelled data to start learning from.

Deep Learning gained popularity in the 1980s with the development of back-propagation—a technique for training neural networks. In the 2000s the evolution of advanced techniques with respect to dropout and rectified linear units (ReLU) helped address core challenges. In 2012, AlexNet, a convolutional neural network focused on image recognition, won awards and regained popularity for mainstream uses in Natural Language Processing, speech recognition and autonomous vehicles.

Common uses include image recognition, Natural Language Processing, speech recognition, fraud detection and autonomous vehicles. As the “deep” in Deep Learning represents the depth of layers in neural networks, a neural network that consists of more than three layers is considered a deep learning algorithm. Deep Learning networks are feed-forward models but they can be trained to back-propagate as well. The latter is especially useful to provide feedback on errors so that the algorithm can be corrected appropriately.`;

questions.slice(95).forEach(item => { item.passage = deepLearningPassage; });
